bithyve/bitcoin-keeper

src/screens/AppSettings/ManageWallets.tsx, src/screens/Inheritance/SetupInheritance.tsx, src/screens/Recovery/ScanQRFileRecovery.tsx, src/screens/Vault/AddIKS.tsx, src/screens/Vault/AddSigningDevice.tsx, src/screens/Vault/VaultDetails.tsx, src/screens/VaultRecovery/VaultConfigurationRecovery.tsx, src/screens/VaultRecovery/VaultRecovery.tsx
Resolved,
-  #3089
- #3090
- #3091
- #3099
- #3101
=> UI fixes (Sprint 21)

src/services/electrum/client.ts
Simplifies and realigns how we add new node connections and test them for availability.
Potentially addresses #3160 as well
=> Electrum client connection test: streamlined

src/components/Modal/PasscodeVerify.tsx, src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/screens/BackupWallet/BackupWallet.tsx, src/screens/ExportSeedScreen/ExportSeedScreen.tsx, src/screens/Send/SendConfirmation.tsx, src/screens/WalletDetails/WalletSettings.tsx
=> Verify passcode during export seed and send

src/core/config.ts, src/core/wallets/factories/WalletFactory.ts, src/core/wallets/interfaces/wallet.ts, src/core/wallets/operations/index.ts, src/core/wallets/operations/utils.ts
Optimises PSBT generation and signing for Wallets and Single-Sig Vaults
Improves:
- MFP generation for wallet(uses cached mfp)
- Address to Pub/Priv-Key generation during adding inputs and signing
Partially addresses #3330
=> Send flow optimisation :: 1/2

src/core/wallets/operations/index.ts, src/core/wallets/operations/utils.ts
Boosts PSBT generation and signing for Multi-Sig Vaults
Improves:
- Address to multi-sig: search optimization
- Optimizes subpath generation
Partially addresses https://github.com/bithyve/bitcoin-keeper/issues/3330
=> Send flow optimisation :: 2/2 

src/core/config.ts, src/core/wallets/interfaces/vault.ts, src/core/wallets/interfaces/wallet.ts, src/core/wallets/operations/index.ts, src/core/wallets/operations/utils.ts, src/storage/realm/realm.ts, src/storage/realm/schema/vault.ts, src/storage/realm/schema/wallet.ts
Introduces pub key caching for both Wallets and Vaults; significantly drawing down the time taken to construct the tx.
Note: Pre-hex signature verification is disabled to improve upon the overall execution time. 
Addresses #3362
=> Vault/Wallet: Tx construction improvements

src/core/wallets/operations/index.ts
Resolves Vault tx signing via signing server.
=> Signing-Server: Subpath fix

src/core/wallets/operations/index.ts
Issue: The block-based fee estimation from Electrum is, on average, resulting in a relatively higher fee than the market.
Fix: We're integrating the [recommended fee](https://mempool.space/docs/api/rest#get-recommended-fees) API from mempool.space in order to provide better fee estimation.
Priority vs Conf-Blocks/Time changes: 
- High: 1 block(10 mins)
- Medium: 3 blocks(30 mins)
- Low: 6 blocks(60 mins)
Note: Electrum's fee estimator remains as a fallback in case the above API fails.
Addresses #3329
=> Fee rates via Mempool

src/screens/Send/SendConfirmation.tsx
Estimates the arrival time based on the latest fee improvements(via mempool.space)
=> Arrival time adjustment

src/components/KeeperTextInput.tsx, src/screens/NFCChannel/ShareWithNfc.tsx, src/screens/Vault/AddSigningDevice.tsx, src/screens/Vault/SignerAdvanceSettings.tsx, src/screens/Vault/VaultSetup.tsx, src/screens/Vault/components/EditDescriptionModal.tsx
Resolved,
- #3440 
- #3441
- #3442
=> Minor fixes

appcenter-pre-build.sh
Downloads whirlpool ios binary from github releases for appcenter build
=> Appcenter ios builld fix

android/app/build.gradle, ios/hexa_keeper.xcodeproj/project.pbxproj, src/core/wallets/factories/VaultFactory.ts, src/hardware/index.ts, src/screens/Recovery/SigninDeviceListRecovery.tsx, src/screens/Recovery/SigningDeviceConfigRecovery.tsx, src/screens/SignTransaction/SignTransactionScreen.tsx, src/screens/SignTransaction/signWithSD.ts, src/screens/SigningDevices/SetupSigningServer.tsx, src/screens/Vault/ChoosePolicyNew.tsx, src/screens/Vault/HardwareModalMap.tsx, src/screens/VaultRecovery/SignersList.tsx, src/services/interfaces/index.ts, src/services/operations/SigningServer.ts, src/store/sagaActions/wallets.ts, src/store/sagas/upgrade.ts, src/store/sagas/wallets.ts
Includes:
- API v3 integration for SS 
- Migration script(v2 to v3) for SS
- Recovery via SigningServer(Relay gets dumped)
Addresses  #3477 #3478 #3479 #3480 #3498
Assisted By https://github.com/bithyve/SigningServer/pull/49
=> Assisted keys(SS)

src/core/wallets/factories/VaultFactory.ts, src/screens/Inheritance/IKSAddEmailPhone.tsx, src/screens/SignTransaction/SignTransactionScreen.tsx, src/screens/SignTransaction/signWithSD.ts, src/screens/SigningDevices/AddIKS.tsx, src/screens/Vault/HardwareModalMap.tsx, src/screens/VaultRecovery/SignersList.tsx, src/screens/VaultRecovery/VaultRecovery.tsx, src/services/interfaces/index.ts, src/services/operations/InheritanceKey.ts, src/store/sagas/upgrade.ts, src/store/sagas/wallets.ts
Includes:
- IKS v3 integration
- cosigner map generation
- Migration script for IKS
=> Assisted keys: IKS Integration

Readme.md
=> Added PGP APK url in readme

src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/screens/Send/CustomPriorityModal.tsx, src/screens/Send/SendConfirmation.tsx, src/screens/Send/WalletSendInfo.tsx
Addresses #3458 #3472 #3409 #3459
=> S&R: UI improvements

src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/screens/Send/CustomPriorityModal.tsx, src/screens/Send/SendConfirmation.tsx, src/screens/Send/WalletSendInfo.tsx
=> S&R Flow: Tx Priority Integration

src/core/wallets/operations/index.ts, src/screens/Send/AddSendAmount.tsx, src/screens/Send/CustomPriorityModal.tsx, src/screens/Send/SendConfirmation.tsx, src/screens/Send/UTXOSelection.tsx, src/store/hooks/sending-utils/UseAvailableTransactionPriorities.tsx, src/store/reducers/send_and_receive.ts, src/store/sagaActions/send_and_receive.ts, src/store/sagas/send_and_receive.ts
Adds: Custom Fee selection ability  #3331 #3474
Fixes: UTXO selection(when sats mode is on) #3518
=> Custom Fee: Integration

src/screens/NewKeeperAppScreen/NewKeeperAppScreen.tsx, src/screens/Recovery/EnterSeedScreen.tsx, src/screens/Recovery/OtherRecoveryMethods.tsx, src/screens/Vault/AddSigningDevice.tsx, src/screens/Vault/VaultDetails.tsx, src/screens/Vault/VaultSetup.tsx
=> Added Test IDs

src/screens/Send/AddSendAmount.tsx, src/screens/Send/SendConfirmation.tsx, src/screens/Send/WalletSendInfo.tsx
=> S&R: Integration and Conversion Fix

package.json, src/core/config.ts, src/core/utils.ts, src/screens/Inheritance/IKSAddEmailPhone.tsx, src/screens/VaultRecovery/VaultRecovery.tsx, src/services/interfaces/index.ts, src/services/operations/InheritanceKey.ts, src/services/operations/encryption/index.ts
Builds upon: https://github.com/bithyve/SigningServer/pull/53
Addresses #3596
=> Inheritance key: Policy Encryption

src/core/wallets/enums/index.ts, src/core/wallets/factories/WalletFactory.ts, src/core/wallets/interfaces/wallet.ts, src/core/wallets/operations/utils.ts, src/hardware/index.ts, src/hardware/passport/index.ts, src/screens/ImportWalletDetailsScreen/AddDetailsFinalScreen.tsx, src/screens/ImportWalletDetailsScreen/ImportWalletDetailsScreen.tsx, src/screens/ImportWalletScreen/ImportWalletScreen.tsx, src/screens/WalletDetails/UpdateWalletDetails.tsx, src/storage/realm/realm.ts, src/storage/realm/schema/wallet.ts, src/store/sagas/wallets.ts
Adds support for:
- mainnet: xprv/xpub, yprv/ypub and zprv/zpub based imports
- testnet: tprv/tpub, uprv/upub and vprv/vpub base imports 
Addresses #3668
=> Import Wallet: Extended Keys based imports

src/assets/images/passwordlock.svg, src/screens/LoginScreen/CreatePin.tsx
=> updates passcode modal

src/screens/ChoosePlanScreen/ChoosePlan.tsx, src/services/electrum/client.ts, src/store/sagas/send_and_receive.ts, src/store/sagas/wallets.ts
=> No play services available and node reconnect error

src/components/ActionCard.tsx, src/components/NotificationStack.tsx, src/screens/Home/HomeScreen.tsx, src/screens/Home/components/BalanceComponent.tsx, src/screens/Home/components/HeaderDetails/components/UAIView.tsx, src/screens/Home/components/HomeScreenWrapper.tsx, src/screens/Inheritance/IKSAddEmailPhone.tsx
=> fix changes in the home screen

src/screens/SigningDevices/ManageSigners.tsx
- fixes UI of manage signers
Issue link: https://github.com/bithyve/bitcoin-keeper/issues/3764
=> fixes the UI of manage signers

src/screens/Vault/AddSigningDevice.tsx
=> IKS & SS: restrictions

src/components/ActionCard.tsx, src/hooks/useSmallDevices.tsx, src/screens/Home/components/WalletInfoCard.tsx, src/screens/Home/components/WalletList.tsx
=> fix home ui changes

src/screens/Inheritance/IKSAddEmailPhone.tsx, src/screens/Vault/AddSigningDevice.tsx, src/screens/Vault/HardwareModalMap.tsx, src/screens/Vault/SignerAdvanceSettings.tsx, src/services/interfaces/index.ts, src/services/operations/InheritanceKey.ts, src/storage/realm/realm.ts, src/storage/realm/schema/vault.ts, src/store/sagas/wallets.ts
=> IKS: multiple config support

src/screens/Vault/AddSigningDevice.tsx
=> Assisted Keys restriction: note

src/screens/ImportWalletDetailsScreen/ImportWalletDetailsScreen.tsx, src/screens/Mix/MixProgress.tsx
=> fix cutting issue

src/assets/images/tick_icon.svg, src/components/HexagonIcon.tsx, src/screens/LoginScreen/CreatePin.tsx, src/screens/Send/SendScreen.tsx
=> fix passcode button disable issue

src/screens/Vault/AddSigningDevice.tsx
=> Assisted Keys: Count based restrictions

package.json, src/core/wallets/operations/BIP85.ts, src/core/wallets/operations/index.ts, src/core/wallets/operations/noble_ecc.ts, src/core/wallets/operations/utils.ts, yarn.lock
Addresses #3815 
- upgrades bip32 to 4.0.0
- removes tiny-secp256k1
- adds noble_ecc
=> Sending to P2TR 

src/screens/Recieve/ReceiveScreen.tsx
=> fix currency icon issue

src/screens/AppSettings/AppSettings.tsx, src/screens/NewKeeperAppScreen/NewKeeperAppScreen.tsx
- adds terms and condition link to website in welcome screen
- adds privacy policy link to website in welcome screen
=> adds the links to website

src/components/CustomButton/CustomButton.tsx, src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/screens/Send/AddSendAmount.tsx, src/screens/Send/SendConfirmation.tsx, src/screens/Send/SendScreen.tsx, src/screens/Send/WalletSendInfo.tsx
=> fix send flow ui issues

src/screens/AppSettings/AppSettings.tsx, src/screens/AppSettings/BackupModal.tsx, src/screens/BackupWallet/WalletBackHistoryScreen.tsx, src/screens/LoginScreen/Login.tsx, src/screens/Vault/SigningDeviceDetails.tsx
=> Minor UI bugs 

src/components/Backup/BackupHealthCheckList.tsx, src/screens/AppSettings/PrivacyAndDisplay.tsx, src/screens/BackupWallet/WalletBackHistoryScreen.tsx, src/screens/EnterWalletDetailScreen/EnterWalletDetailScreen.tsx
=> fix wallet description and wallet backup ui

src/components/NotificationStack.tsx, src/screens/Send/SendConfirmation.tsx
=> fix  uai crashing issue

src/components/Switch/MonthlyYearlySwitch.tsx, src/screens/ChoosePlanScreen/ChoosePlan.tsx
=> adds the monthly yearly switch

src/components/Carousel/ChoosePlanCarouselItem.tsx
- remove floating value from the subscription value
=> removes the decimal part from subscription value

src/screens/Send/AddSendAmount.tsx, src/screens/Send/SendConfirmation.tsx
- fixes the color issue in send flow
=> fixes the color issue

src/core/wallets/operations/utils.ts, src/screens/Recieve/ReceiveScreen.tsx, src/screens/Send/SendScreen.tsx
- fixes the send issue in wallet to address having specified amount
=> fixes the send issue in wallet to address having amount in url

src/screens/Send/SendConfirmation.tsx
- fixes the sats conversion issue
- fixes the text overflow issue is sent success modal
=> fixes the conversion and text overflow issue

src/components/Carousel/ChoosePlanCarouselItem.tsx
- fixes the subscription amount issue
=> fixes the subscription amount issue

src/components/SettingComponent/VersionHistoryList.tsx, src/screens/AppSettings/AppVersionHistoty.tsx, src/screens/ImportWalletDetailsScreen/AddDetailsFinalScreen.tsx
- fixes the version history ui issue
- makes the path field in import wallet uneditable
=> fixes the version history ui issue

src/screens/EnterWalletDetailScreen/EnterWalletDetailScreen.tsx
=> Add new wallet: taproot fix

src/screens/Vault/HardwareModalMap.tsx, src/screens/Vault/SignerAdvanceSettings.tsx, src/services/backend/SigningServer.ts
=> Assisted keys: Health-check and Change signer-type 

src/screens/Send/SendConfirmation.tsx, src/screens/Vault/VaultDetails.tsx
- https://github.com/bithyve/bitcoin-keeper/issues/4148
- https://github.com/bithyve/bitcoin-keeper/issues/4109
=> changes the content

src/screens/Vault/HardwareModalMap.tsx
=> SS health-check: OTP modal integration

src/screens/Vault/HardwareModalMap.tsx, src/services/backend/InheritanceKey.ts
=> IKS: health-check integration

src/screens/InheritanceToolsAndTips/BackupRecovery.tsx, src/screens/InheritanceToolsAndTips/KeySecurity.tsx, src/screens/Send/AddSendAmount.tsx, src/store/reducers/storage.ts, src/utils/utilities.ts
=> Feature/update UI add send amount

ios/Podfile.lock, package.json, yarn.lock
Removes unused dependency, replaced by node-rsa
=> dump: react-native-rsa-native

src/screens/WalletDetails/UpdateWalletDetails.tsx
Removes BIP85 derivation path, adds back standard hierarchal path.
=> Derivation path - using standard, removed BIP-85

src/screens/EnterWalletDetailScreen/EnterWalletDetailScreen.tsx
- https://github.com/bithyve/bitcoin-keeper/issues/4248
=> Wallet modal cta

src/components/Modal/PasscodeVerify.tsx, src/screens/Vault/SignerAdvanceSettings.tsx
- https://github.com/bithyve/bitcoin-keeper/issues/4219
- https://github.com/bithyve/bitcoin-keeper/issues/4183
=> adds the email text in delete email

src/assets/images/master_key.svg, src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/screens/Home/HomeScreen.tsx, src/screens/InheritanceToolsAndTips/components/MasterRecoveryKey.tsx, src/screens/Send/SendConfirmation.tsx
=> adds symbol in send confirmation flow

src/hooks/useSubscriptionLevel.ts, src/screens/Vault/AddSigningDevice.tsx
=> Assisted keys: Subscription-based shells

src/screens/ExportSeedScreen/ExportSeedScreen.tsx, src/screens/Vault/HardwareModalMap.tsx
Mobile key HC as Recovery Key flow 
#4207
=> recovery key hc flow for Mobile key

src/components/KeeperHeader.tsx, src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/hardware/index.ts, src/screens/AppSettings/ManageWallets.tsx, src/screens/Send/SendConfirmation.tsx, src/screens/Vault/VaultDetails.tsx
- https://github.com/bithyve/bitcoin-keeper/issues/4316
=> Quick fix issues

src/screens/Home/components/CurrencyInfo.tsx, src/screens/LoginScreen/Login.tsx
-Notification permission was missing for IOS so added permission on LoginPage.
Also, I have added a UI fix in the same PR where the text was slicing.
=> Notification

src/services/wallets/operations/index.ts
=> Dynamic testnet fee: mempool integration

src/screens/SignTransaction/SignTransactionScreen.tsx
=> Signing post password confirmation for mobile key

src/components/WalletCard.tsx, src/screens/InheritanceToolsAndTips/InheritanceToolsAndTips.tsx, src/screens/InheritanceToolsAndTips/components/UpgradeSubscription.tsx, src/screens/Vault/VaultMigrationController.tsx
=> Feature/small device UI

src/hardware/index.ts
=> Fix: Network error for xpubs

src/screens/Vault/AddSigningDevice.tsx, src/screens/Vault/SigningDeviceDetails.tsx, src/screens/Vault/VaultMigrationController.tsx
=> Updated: Signer rotation flow

App.tsx, ios/Podfile, ios/Podfile.lock, ios/cloudbackup/CloudBackupHelper.swift, ios/cloudbackup/cloudbackup.h, ios/cloudbackup/cloudbackup.m, ios/hexa_keeper.xcodeproj/project.pbxproj, ios/hexa_keeper/Info.plist, ios/hexa_keeper/hexa_keeper.entitlements, ios/hexa_keeper_dev-Info.plist, ios/hexa_keeper_dev.entitlements, src/assets/images/check.svg, src/assets/images/check.tsx, src/components/Modal/ConciergeOnboardingModal.tsx, src/models/enums/ConciergeTag.ts, src/navigation/Navigator.tsx, src/screens/AddSigner/SignerCard.tsx, src/screens/AppSettings/AppSettings.tsx, src/screens/CloudBackup/CloudBackupScreen.tsx, src/store/reducers/concierge.ts, src/store/reducers/storage.ts, src/store/sagaActions/concierge.ts, src/store/sagas/bhr.ts, src/store/sagas/concierge.ts, src/store/sagas/index.ts, src/store/store.ts
=> Concierge onboarding screens and iCloud fix

src/hooks/useTestSats.tsx, src/services/backend/Relay.ts, src/services/wallets/operations/index.ts
=> Mock fee-rates and Testnet sats

src/screens/AppSettings/ChangeLanguage.tsx
=> fixes navigation issue in currency selection

src/screens/AddSigner/SignerCard.tsx, src/screens/AppSettings/ChangeLanguage.tsx
- https://github.com/bithyve/bitcoin-keeper/issues/4409
=> fixes the checkbox issue in signer card

src/components/Modal/PasscodeVerify.tsx, src/screens/Send/SendConfirmation.tsx
=> fixes crash in passcode on send flow

src/hardware/index.ts
changes ledger description.
old: Trusted signers from SatoshiLabs
new: Popular signers like Nano S and Nano X
=> updates ledger description

src/components/NotificationStack.tsx, src/screens/Send/SendConfirmation.tsx
Vault send issue is fixed:
It was because the component was coupling all vault transfers as auto transfers
https://github.com/bithyve/bitcoin-keeper/issues/4436
=> Fix/vault_send_crash 

src/components/ActionCard.tsx, src/hooks/useSmallDevices.tsx
- https://github.com/bithyve/bitcoin-keeper/issues/4400
- Conflicts Resolved
=> Conflicts Resolved and Cards made Dynamic

src/hooks/useSmallDevices.tsx, src/screens/Vault/AddSigningDevice.tsx
=> fix glitch issue

src/components/CardPill.tsx, src/components/OptionCard.tsx, src/hooks/useSmallDevices.tsx, src/navigation/themes.js, src/screens/InheritanceToolsAndTips/AssistedKeysSlider.tsx, src/screens/InheritanceToolsAndTips/InheritanceToolsAndTips.tsx, src/screens/InheritanceToolsAndTips/TipsSlider.tsx, src/screens/InheritanceToolsAndTips/components/AdditionalSignerDetailsTemplate.tsx, src/screens/InheritanceToolsAndTips/components/AssistedKeysSliderContent.tsx, src/screens/InheritanceToolsAndTips/components/BackupAndRecoveryTips.tsx, src/screens/InheritanceToolsAndTips/components/LetterOfAttorney.tsx, src/screens/InheritanceToolsAndTips/components/MasterRecoveryKey.tsx, src/screens/InheritanceToolsAndTips/components/RecoveryInstruction.tsx, src/screens/InheritanceToolsAndTips/components/RecoveryPhraseTemplate.tsx, src/screens/InheritanceToolsAndTips/components/SafeGuardingTips.tsx, src/screens/InheritanceToolsAndTips/components/SafeKeepingTips.tsx, src/screens/InheritanceToolsAndTips/components/TrustedContactsTemplate.tsx, src/screens/InheritanceToolsAndTips/components/UpgradeSubscription.tsx, src/screens/InheritanceToolsAndTips/components/WalletConfigurationFiles.tsx, src/theme/Colors.ts
=> adds dark mode in inheritance flow

src/hardware/index.ts, src/screens/SignTransaction/SignerModals.tsx, src/screens/Vault/SignerAdvanceSettings.tsx, src/screens/WalletDetails/CosignerDetails.tsx, src/services/wallets/operations/index.ts
=> Signing enhancements

src/screens/SignTransaction/SignerModals.tsx, src/screens/SigningDevices/HandleFileScreen.tsx, src/screens/Vault/HardwareModalMap.tsx
=> Fix: file import crash on setup

src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/screens/AppSettings/ChangeLanguage.tsx, src/screens/AppSettings/ManageWallets.tsx, src/screens/SigningDevices/InputSeedWordSigner.tsx, src/screens/Vault/VaultConfigurationRecreation.tsx
Addresses:
#4484
#4540
#4541
#4544
=> adds funds transfer modal on hide vault

src/hardware/index.ts, src/screens/Home/components/BalanceComponent.tsx, src/screens/Home/components/WalletInfoCard.tsx, src/screens/Send/SendConfirmation.tsx, src/screens/SignTransaction/SignWithColdCard.tsx, src/screens/SignTransaction/SignerModals.tsx
=> changes mk4 option to coldcard

src/services/wallets/factories/VaultFactory.ts
=> Fix: Cosigners registration for Assisted Keys

src/components/KeeperHeader.tsx, src/screens/AppSettings/AppBackupSettings.tsx, src/screens/Send/AddSendAmount.tsx, src/screens/Send/SendScreen.tsx, src/screens/Send/WalletSendInfo.tsx
=> fixes available balance not showing at the right place

src/screens/EnterWalletDetailScreen/EnterWalletDetailScreen.tsx
Related to #4285 
Added `importDetails` object when wallet type is imported
=> Fix: backup with keeper error 

src/components/OptionCard.tsx, src/components/WalletCard.tsx, src/screens/EnterWalletDetailScreen/DerivationPathModal.tsx, src/screens/Vault/SignerAdvanceSettings.tsx, src/screens/Vault/SigningDeviceList.tsx, src/screens/Vault/VaultSettings.tsx
Addresses:
#4460
#4450
#4445
#4497
#4516
=> fixes dropdown not showing selected wallet purpose

src/assets/images/efficiency.svg, src/assets/images/privacy.svg, src/assets/images/scaling.svg, src/assets/images/security.svg, src/components/KeeperModal.tsx, src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/screens/EnterWalletDetailScreen/EnterWalletDetailScreen.tsx
=> adds taproot modal

src/components/OptionCard.tsx
=> fixes option card styling

src/navigation/Navigator.tsx, src/navigation/types.ts, src/screens/ExportSeedScreen/ExportSeedScreen.tsx, src/screens/Vault/SignerAdvanceSettings.tsx, src/services/backend/InheritanceKey.ts, src/services/backend/SigningServer.ts, src/store/migrations.ts, src/store/reducers/settings.ts, src/store/store.ts, src/utils/service-utilities/encryption.ts
=> IKS+: OTB integration

src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/screens/NewKeeperAppScreen/NewKeeperAppScreen.tsx, src/screens/Vault/SigningDeviceList.tsx, src/screens/WalletDetails/WalletDetails.tsx
Addresses:
#4468
#4495
#4494
#4493
#4506
=> updates content

src/navigation/Navigator.tsx, src/screens/ExportSeedScreen/ExportSeedScreen.tsx
Derivation path(BIP-48) is also included on the OTB screen.
Addresses #4318
=> OTB: Derivation path 

src/services/wallets/operations/index.ts
- Removes Electrum fallback for Testnet fee
- Bumps static testnet fee(keeping up w/ testnet3, somehow)
=> Mock fee bump

src/screens/Vault/AddSigningDevice.tsx
=> adds inheritance modal in Add Keys screen

src/components/KeeperHeader.tsx, src/components/KeeperModal.tsx, src/models/enums/ConciergeTag.ts, src/screens/AddWalletScreen/AddWallet.tsx, src/screens/AppSettings/AppVersionHistoty.tsx, src/screens/EnterWalletDetailScreen/EnterWalletDetailScreen.tsx, src/screens/ImportWalletScreen/ImportWalletScreen.tsx, src/screens/InheritanceToolsAndTips/InheritanceToolsAndTips.tsx, src/screens/NewKeeperAppScreen/NewKeeperAppScreen.tsx, src/screens/QRScreens/ScanQR.tsx, src/screens/SigningDevices/SetupCollaborativeWallet.tsx, src/screens/Vault/SigningDeviceDetails.tsx, src/screens/Vault/SigningDeviceList.tsx, src/screens/Vault/VaultDetails.tsx, src/screens/WalletDetails/components/LearnMoreModal.tsx
=> adds redirection to keeper concierge on need more help press

src/screens/Vault/HardwareModalMap.tsx, src/screens/WalletDetails/WalletSettings.tsx
=> Fix: Transfer policy and HC support file based

src/screens/SigningDevices/ManageSigners.tsx, src/screens/Vault/AddSigningDevice.tsx
Adds shells to Manage Keys page for Assisted Keys and prompts the user to set them up. 
Addresses #4317
=> Manage Keys: adds Assisted Keys' shells

src/utils/service-utilities/config.ts
=> Hot wallets: limit bump

src/hardware/index.ts
=> Status updates for Assisted Keys

src/components/XPub/TransferPolicy.tsx, src/constants/Bitcoin.tsx, src/hooks/useBalance.tsx
=> fixes issues in transfer policy

package.json, src/services/backend/InheritanceKey.ts, src/services/backend/SigningServer.ts, src/store/reducers/settings.ts, src/utils/service-utilities/encryption.ts
=> RSA Keypair gen: ramp up

src/hooks/useSignerIntel.tsx, src/screens/Inheritance/InheritanceStatus.tsx, src/screens/SigningDevices/ManageSigners.tsx, src/screens/Vault/AddSigningDevice.tsx
Includes
- Assisted keys deactivation comms
- IKS activation scheme
- Manage Keys shell bug fix 
Addresses #4600
=> Assisted Keys - Updates

src/screens/AppSettings/ManageWallets.tsx, src/screens/SigningDevices/SetupCollaborativeWallet.tsx
=> Cw enhancements

src/screens/InheritanceToolsAndTips/InheritanceToolsAndTips.tsx, src/screens/Recovery/EnterSeedScreen.tsx, src/screens/Send/SendScreen.tsx, src/screens/Vault/AddSigningDevice.tsx
=> fixes bugs 

src/services/backend/InheritanceKey.ts, src/services/backend/SigningServer.ts, src/store/sagas/upgrade.ts
=> Migration: Assisted Keys' cosigners

src/context/Localization/language/en.json, src/context/Localization/language/es.json
=> fixes content

src/screens/SignTransaction/signWithSD.ts, src/screens/Vault/HardwareModalMap.tsx, src/services/wallets/factories/VaultFactory.ts
=> Seed Key: Invalid import check

src/navigation/contants.ts, src/screens/AppSettings/ManageWallets.tsx, src/screens/EnterWalletDetailScreen/DerivationPathModal.tsx, src/screens/Send/AddSendAmount.tsx, src/screens/Send/SendConfirmation.tsx, src/screens/Send/SendScreen.tsx, src/screens/Vault/AddSigningDevice.tsx
=> fixes send flow when coming from manage wallets

src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/screens/Vault/SignerAdvanceSettings.tsx
=> updates content for one time backup

src/services/electrum/client.ts
=> Electrum client: obj access fix

src/screens/Vault/HardwareModalMap.tsx, src/screens/Vault/SignerAdvanceSettings.tsx, src/services/backend/InheritanceKey.ts, src/store/reducers/storage.ts
Addresses #4655 
Dependency https://github.com/bithyve/SigningServer/pull/110
=> IKS OTB: request-based

src/components/Backup/BackupHealthCheckList.tsx, src/components/Backup/HealthCheckComponent.tsx, src/components/SeedWordBackup/ConfirmSeedWord.tsx, src/components/UTXOsComponents/UTXOSelectionTotal.tsx, src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/screens/AddWalletScreen/AddWallet.tsx, src/screens/AppSettings/AppBackupSettings.tsx, src/screens/ExportSeedScreen/ExportSeedScreen.tsx, src/screens/SigningDevices/SetupCollaborativeWallet.tsx, src/screens/Vault/AddSigningDevice.tsx
=> Fixes various minor issues

src/screens/InheritanceToolsAndTips/components/UpgradeSubscription.tsx, src/screens/SignTransaction/SignerModals.tsx, src/screens/SigningDevices/SetupSigningServer.tsx, src/screens/Vault/ChoosePolicyNew.tsx, src/screens/Vault/HardwareModalMap.tsx, src/screens/Vault/SignerAdvanceSettings.tsx, src/screens/Vault/SigningDeviceList.tsx
=> adds upgrade option on assisted keys

src/screens/SignTransaction/SignTransactionScreen.tsx, src/screens/SignTransaction/signWithSD.ts, src/screens/Vault/HardwareModalMap.tsx, src/services/backend/InheritanceKey.ts, src/store/reducers/storage.ts
Addresses https://github.com/bithyve/bitcoin-keeper/issues/4712
=> IKS: Signing integration

src/screens/ExportSeedScreen/ExportSeedScreen.tsx, src/screens/Vault/SignerAdvanceSettings.tsx
=> fixes issues in OTB flow

src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/models/enums/ConciergeTag.ts, src/screens/CloudBackup/CloudBackupScreen.tsx, src/screens/Send/SendConfirmation.tsx
=> updates uai auto transfer screen

src/screens/SignTransaction/SignTransactionScreen.tsx, src/store/reducers/cachedTxn.ts
Resolves crash due to:
- duplicate state initialisation
- missing route param
Also addresses #4663
=> Sign transaction: crash fixes & timer persistence

src/screens/SignTransaction/SignTransactionScreen.tsx, src/store/reducers/send_and_receive.ts, src/store/reducers/storage.ts
=> IKS: multiple signing requests

src/screens/CloudBackup/CloudBackupScreen.tsx, src/store/sagas/bhr.ts
fix: current timestamp and crash when empty password
=> Timestamp issue and empty password crash fix

src/screens/Vault/VaultMigrationController.tsx
=> Bug fixes and enhancements

src/screens/Send/SendConfirmation.tsx, src/screens/Vault/VaultDetails.tsx
=> Cached Tx: UTXO Validation

src/screens/Send/SendConfirmation.tsx, src/screens/SignTransaction/SignTransactionScreen.tsx
=> Cached Tx: Discard CTA

src/screens/Send/SendConfirmation.tsx, src/screens/SignTransaction/SignTransactionScreen.tsx, src/screens/SignTransaction/SignerList.tsx, src/screens/Vault/SignerAdvanceSettings.tsx, src/screens/Vault/VaultDetails.tsx
Addresses:
- https://github.com/bithyve/bitcoin-keeper/issues/4626
- Cached Txs ordering
- https://github.com/bithyve/bitcoin-keeper/issues/4731
=> Cached Tx & IKS fixes

src/hooks/useSignerIntel.tsx, src/screens/Vault/AddSigningDevice.tsx
=> IKS: activation scheme update

src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/screens/Send/SendConfirmation.tsx
=> Tx priority: content fix

src/components/SeedWordBackup/ConfirmSeedWord.tsx, src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/screens/ExportSeedScreen/ExportSeedScreen.tsx, src/screens/Vault/SignerAdvanceSettings.tsx
=> updates OTB flow according to xd

src/screens/SignTransaction/SignTransactionScreen.tsx, src/screens/SignTransaction/SignerList.tsx
=> adds real-time iks signing timer

src/screens/AddSigner/SignerCard.tsx, src/screens/Vault/AddSigningDevice.tsx
Replaces https://github.com/bithyve/bitcoin-keeper/pull/4759 and Addresses #https://github.com/bithyve/bitcoin-keeper/issues/4752
=> Assisted Keys: Disable invalid keys

src/screens/Send/SendConfirmation.tsx, src/screens/Vault/AddSigningDevice.tsx
=> fixes crash and add key option in Collaborative Wallet

src/screens/Send/SendConfirmation.tsx
=> chore: Reset vault migration on SendConfirmation component mount

src/screens/UTXOManagement/UTXOLabeling.tsx
=> Resolved - Label UX needs polish 

src/screens/QRScreens/ScanQR.tsx
=> fix: Add condition to check QR code type before setting data

ios/cloudbackup/CloudBackupHelper.swift, ios/hexa_keeper.xcodeproj/project.pbxproj, ios/hexa_keeper/hexa_keeper.entitlements, ios/hexa_keeper_dev-Info.plist, ios/hexa_keeper_dev.entitlements, src/screens/Vault/VaultSettings.tsx
- Vault fingerprint removed
- Fixed: ios cloud backup not working
=> Cloud backup

src/screens/AddSigner/SignerCard.tsx, src/screens/Send/SendConfirmation.tsx
=> updates ui of transaction priority modal

src/hardware/index.ts, src/screens/SignTransaction/SignWithColdCard.tsx
- Removed timestamp from name
- Go back after signing
=> Coldcard fix

src/screens/SigningDevices/DeleteKeys.tsx, src/screens/Vault/SignerAdvanceSettings.tsx
=> adds hide/unhide for assisted keys

src/screens/AddWalletScreen/AddWallet.tsx, src/screens/EnterWalletDetailScreen/EnterWalletDetailScreen.tsx, src/screens/ImportWalletScreen/ImportWalletScreen.tsx, src/screens/InheritanceToolsAndTips/InheritanceToolsAndTips.tsx, src/screens/QRScreens/ScanQR.tsx, src/screens/SigningDevices/SetupCollaborativeWallet.tsx, src/screens/Vault/SigningDeviceDetails.tsx, src/screens/Vault/SigningDeviceList.tsx, src/screens/Vault/VaultConfigurationRecreation.tsx, src/screens/Vault/VaultDetails.tsx, src/screens/WalletDetails/components/LearnMoreModal.tsx
=> fixes modal behavior when concierge triggers

src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/screens/CloudBackup/CloudBackupScreen.tsx, src/screens/InheritanceToolsAndTips/TipsSlider.tsx, src/store/reducers/settings.ts
=> adds modal in cloud backup

src/screens/Send/CustomPriorityModal.tsx, src/screens/Send/SendConfirmation.tsx
=> Transaction Priority: Updates

src/screens/Vault/AddSigningDevice.tsx, src/screens/Vault/HardwareModalMap.tsx
=> Adds signing server modal

src/hardware/index.ts, src/screens/Vault/HardwareModalMap.tsx
=> Signing Server: Recovery Integration

src/screens/Send/SendConfirmation.tsx
=> fixes transaction priority modal visibility issue

src/components/NotificationStack.tsx
=> WIP: adds entry and skip animation in notification stack

src/screens/WalletDetails/WalletSettings.tsx
=> removes fingerprint from wallet settings

src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/screens/InheritanceToolsAndTips/components/PersonalCloudBackup.tsx, src/screens/Vault/HardwareModalMap.tsx
=> adds cloud name dynamically

src/components/NotificationStack.tsx
=> fixes uai animation lag

src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/screens/Send/SendConfirmation.tsx
=> adds logic for high fee alert for different scenarios

src/screens/Vault/HardwareModalMap.tsx
=> makes mobile key health check flow from uai consistent

src/screens/Send/SendConfirmation.tsx, src/store/reducers/settings.ts
=> makes non sats the default mode

src/components/SelectWalletModal.tsx, src/screens/AddSigner/SignerCard.tsx
=> adds component for select wallet modal

src/screens/Channel/ConnectChannel.tsx, src/screens/ImportWalletScreen/ImportWalletScreen.tsx, src/screens/QRScreens/RegisterWithChannel.tsx, src/screens/QRScreens/ScanQR.tsx, src/screens/QRScreens/SignWithChannel.tsx, src/screens/Recovery/ScanQRFileRecovery.tsx, src/screens/Send/SendScreen.tsx, src/screens/Vault/VaultConfigurationRecreation.tsx
=> unmounts camera when navigating to next screen

src/assets/images/analytics-illustration.svg, src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/screens/Home/InititalAppController.tsx, src/screens/LoginScreen/CreatePin.tsx, src/storage/realm/RealmProvider.tsx, src/store/reducers/login.ts, src/store/reducers/settings.ts
=> add share analytics modal on login

src/screens/Vault/ChoosePolicyNew.tsx, src/screens/Vault/SignerAdvanceSettings.tsx, src/screens/Vault/SigningDeviceDetails.tsx, src/store/reducers/wallets.ts, src/store/sagas/wallets.ts
=> Fixes updated policy not being reflected on ui

src/hardware/index.ts
=> changes content for seed key

src/screens/Send/AddSendAmount.tsx, src/screens/Send/SendConfirmation.tsx, src/screens/Send/SendScreen.tsx, src/services/wallets/operations/index.ts
=> Testnet: Spending Unconfirmed Balance

android/app/build.gradle, ios/hexa_keeper.xcodeproj/project.pbxproj, ios/hexa_keeper/Info.plist, ios/hexa_keeperTests/Info.plist, ios/hexa_keeper_dev-Info.plist, package.json, src/screens/CloudBackup/CloudBackupScreen.tsx, src/store/sagas/bhr.ts, src/store/sagas/wallets.ts
- Auto bsms backup on cloud #4817
- build v1.2.11(379)
=> Auto cloud backup

src/screens/Inheritance/IKSAddEmailPhone.tsx, src/screens/Vault/HardwareModalMap.tsx, src/screens/Vault/SignerAdvanceSettings.tsx, src/store/reducers/storage.ts, src/store/sagas/wallets.ts
Fixes alert(email) and notification(FCM) updates for the subsequent host(inheritor) of the inheritance key.
Addresses #4776 and #4924
=> IKS Alerts and Notification

src/screens/Home/components/WalletList.tsx, src/screens/Send/SendConfirmation.tsx
Addresses:
- https://github.com/bithyve/bitcoin-keeper/issues/4928
- https://github.com/bithyve/bitcoin-keeper/issues/4907
=> Auto-sync and CachedTx fix

src/screens/Vault/VaultConfigurationRecreation.tsx
=> minor ui fix

android/app/build.gradle, ios/hexa_keeper.xcodeproj/project.pbxproj, ios/hexa_keeper/Info.plist, ios/hexa_keeperTests/Info.plist, ios/hexa_keeper_dev-Info.plist, package.json
=> Build v1.2.12(383)

src/screens/AppSettings/Node/NodeSettings.tsx, src/screens/Home/InititalAppController.tsx, src/screens/LoginScreen/CreatePin.tsx, src/screens/Vault/SigningDeviceDetails.tsx
=> fixes node connection toast showing everytime app refreshed

src/navigation/Navigator.tsx, src/navigation/types.ts, src/screens/Recovery/SigningDeviceConfigRecovery.tsx, src/screens/SigningDevices/PassportConfigRecovery.tsx
=> adds flow for recovering vault from passport

src/components/NotificationStack.tsx, src/screens/FeeInsights/FeeGraph.tsx
=> fixes fee insights uai not getting dismissed

package.json, src/models/interfaces/Subscription.ts, src/screens/ChoosePlanScreen/ChoosePlan.tsx
Added promo code support for android
=> Promo codes

src/components/NotificationStack.tsx, src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/hooks/useUaiStack.ts
=> fixes uai glitch caused by iks request

src/components/KeyAddedModal.tsx, src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/navigation/types.ts, src/screens/Channel/ConnectChannel.tsx, src/screens/SigningDevices/ManageSigners.tsx, src/screens/SigningDevices/SetupColdCard.tsx, src/screens/SigningDevices/SetupSigningServer.tsx, src/screens/SigningDevices/SetupTapsigner.tsx, src/screens/Vault/AddSigningDevice.tsx, src/screens/Vault/HardwareModalMap.tsx, src/screens/Vault/MockWrapper.tsx, src/screens/Vault/NFCScanner.tsx
=> adds key added success message

src/screens/AppSettings/PrivacyAndDisplay.tsx, src/screens/LoginScreen/Login.tsx, src/screens/Vault/VaultConfigurationRecreation.tsx
=> fixes incorrect passcode modal and error message logic

src/services/wallets/factories/VaultFactory.ts
Addresses https://github.com/bithyve/bitcoin-keeper/issues/5009
=> Vault factory: multisig-only

src/constants/defaultData.tsx, src/hardware/signerSetup.ts, src/screens/AppSettings/AppBackupSettings.tsx, src/screens/SigningDevices/DeleteKeys.tsx, src/store/sagas/bhr.ts, src/store/sagas/storage.ts, src/store/sagas/wallets.ts
Addresses #4831 
Canary Wallet option for Recovery Key.
Create RK Signing Key on New Account creation and Account recovery.
Hide RK-SK from delete keys screen.
=> Fixes Recovery Key settings #4831

src/components/NotificationStack.tsx, src/components/SelectWalletModal.tsx, src/screens/Send/SendConfirmation.tsx, src/store/reducers/send_and_receive.ts, src/store/sagas/send_and_receive.ts
Addresses #4780 
Updated SendConfirmation screen for Auto Transfers.
1. Condition to hide HIDDEN vaults from Auto Transfer Vault selection modal.
2. Updated transfer card ui for Auto Transfers.
3. Enabled transaction priority with calculation for ARRIVAL TIME and non actionable card.
4. Updated UI for footer CTA's
=> Send Confirmation screen multiple versions. #4780

src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/screens/AppSettings/ManageWallets.tsx
Addresses #4814 
1. Delete Vaults with funds, updated delete modal.
2. Fix crash on transfer funds and cancel.
3. Hide delete option for Wallets with funds.
=>  fixes Deleting Vaults Without Transferring Funds #4814

src/components/XPub/TransferPolicy.tsx
Addresses #4943 
Task 3: Edit Transfer Policy Modal, Default value should not be 0 and placeholder should be visible for it.
=> fixes Transfer Policy Changes: Remove the default input field #4943

src/screens/Vault/AddSigningDevice.tsx, src/store/sagas/uai.ts
Addresses #5061 
Filtered out hidden signers when creating a vault.
Filtered out hidden signers for health check.
=> Fixes hidden signers should not be visible when creating Vaults. #5061

src/components/KeeperTextInput.tsx, src/screens/ChoosePlanScreen/ChoosePlan.tsx
Fixes issue with red border color on input fields.
=> fix: TextInputErrorBorder

src/services/wallets/factories/VaultFactory.ts
Reverts bithyve/bitcoin-keeper#5010
=> Revert "Vault factory: multisig-only"

android/app/build.gradle, ios/hexa_keeper.xcodeproj/project.pbxproj, ios/hexa_keeper/Info.plist, ios/hexa_keeperTests/Info.plist, ios/hexa_keeper_dev-Info.plist
=> build 386 android/ios

src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/screens/Vault/HardwareModalMap.tsx, src/screens/Vault/SignerAdvanceSettings.tsx
=> repositions 2fa of signing server

src/screens/Channel/ConnectChannel.tsx, src/screens/QRScreens/RegisterWithChannel.tsx, src/screens/QRScreens/SignWithChannel.tsx, src/screens/Vault/SigningDeviceDetails.tsx
=> fixes signing devices content

src/components/CameraUnauthorized.tsx, src/screens/QRScreens/ScanQR.tsx, src/screens/Vault/VaultConfigurationRecreation.tsx
=> adds option to allow camera access

src/screens/AddWalletScreen/AddWallet.tsx, src/screens/CloudBackup/CloudBackupScreen.tsx, src/screens/EnterWalletDetailScreen/EnterWalletDetailScreen.tsx, src/screens/ImportWalletScreen/ImportWalletScreen.tsx, src/screens/InheritanceToolsAndTips/InheritanceToolsAndTips.tsx, src/screens/QRScreens/ScanQR.tsx, src/screens/SigningDevices/SetupCollaborativeWallet.tsx, src/screens/Vault/SigningDeviceDetails.tsx, src/screens/Vault/SigningDeviceList.tsx, src/screens/Vault/VaultConfigurationRecreation.tsx, src/screens/Vault/VaultDetails.tsx, src/screens/WalletDetails/components/LearnMoreModal.tsx, src/store/reducers/settings.ts
=> sets sats mode on by default

android/app/build.gradle, ios/hexa_keeper.xcodeproj/project.pbxproj, ios/hexa_keeper/Info.plist, ios/hexa_keeperTests/Info.plist, ios/hexa_keeper_dev-Info.plist
=> release 389

src/services/wallets/operations/index.ts
Workaround for testnet3 fee spikes
Addresses #5134
=> Testnet: fee threshold

src/components/Backup/HealthCheckComponent.tsx, src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/screens/ChoosePlanScreen/ChoosePlan.tsx, src/screens/Vault/HardwareModalMap.tsx
=> adds learn how bullet in seed signer modal

src/components/Backup/BackupHealthCheckList.tsx, src/components/KeeperFooter.tsx, src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/screens/AppSettings/PrivacyAndDisplay.tsx, src/screens/Vault/SigningDeviceDetails.tsx
=> adds hc modal in passcode reset

src/components/NotificationStack.tsx, src/hooks/useUaiStack.ts
=> fixes uai animation behaviour

src/screens/LoginScreen/CreatePin.tsx, src/utils/utilities.ts
=> fixes passcode input lag on older devices

src/components/NotificationStack.tsx, src/context/Localization/language/en.json, src/context/Localization/language/es.json
Addresses #5022 
Added source wallet name in Auto transfer modal.
=> fixes Auto transfer wallet logic needs updation? #5022

android/app/build.gradle, ios/hexa_keeper.xcodeproj/project.pbxproj, ios/hexa_keeper/Info.plist, ios/hexa_keeperTests/Info.plist, ios/hexa_keeper_dev-Info.plist
release 394
Fixes version mismatch issue.
=> release 394

src/services/wallets/factories/VaultFactory.ts, src/services/wallets/operations/index.ts, src/services/wallets/operations/utils.ts
Addresses https://github.com/bithyve/bitcoin-keeper/issues/5096
=> Vault: Explicit purpose derivation based on script type

src/components/KeyAddedModal.tsx
=> fixes crash and consistent Ui flow for External Key Added Modal #5389

src/screens/SigningDevices/SetupCollaborativeWallet.tsx
=> fixes description not showing in setup collab wallet

src/screens/Contact/AssociateContact.tsx, src/screens/Contact/EditContact.tsx, src/screens/Vault/SigningDeviceDetails.tsx
Addresses
Key details isn't showing contact image #5486 
Edit contact shows null at the end of the contact name #5488 
Associate Contact modal cancel button doesn't work #5489
=> fixes Associate contact issues 

src/screens/Contact/AddContact.tsx, src/screens/Contact/AssociateContact.tsx, src/screens/Contact/EditContact.tsx, src/screens/SigningDevices/ManageSigners.tsx, src/screens/Vault/AdditionalDetails.tsx
=> Don't show key added modal on update contact details

src/components/Instruction.tsx, src/screens/Vault/HardwareModalMap.tsx
=> fixes floating urls in jade modal

package.json, yarn.lock
updating react-native-qrcode-svg version due to crashing issue
=> Updates react-native-qrcode-svg to 6.3.2

android/app/build.gradle, ios/Podfile.lock, ios/hexa_keeper.xcodeproj/project.pbxproj, ios/hexa_keeper/Info.plist, ios/hexa_keeperTests/Info.plist, ios/hexa_keeper_dev-Info.plist, yarn.lock
=> release 411

src/screens/Contact/AssociateContact.tsx, src/services/documents/index.ts
Key details isn't showing contact image #5486 
Added optional chaining in filter contacts for error checks
=> fixes contact image persistance on android 5486

src/hardware/portal/index.ts, src/screens/Recieve/ReceiveScreen.tsx, src/screens/SignTransaction/SignerModals.tsx, src/screens/SigningDevices/SetupPortal.tsx, src/screens/Vault/HardwareModalMap.tsx, src/screens/Vault/SignerAdvanceSettings.tsx
Address verification and Register from Send and Receive on Portal #5517
=> Portal address verification #5517

src/screens/CloudBackup/CloudBackupScreen.tsx
=> Fix recent history title placement for cloud backup

src/screens/SigningDevices/SetupCollaborativeWallet.tsx
=> Filter out hidden mobile keys on collaborative vault setup

src/components/Buttons.tsx, src/screens/Send/SendConfirmation.tsx, src/screens/Send/SendSuccessfulContent.tsx, src/screens/SignTransaction/SignTransactionScreen.tsx, src/screens/Vault/SigningDeviceDetails.tsx
=> fixes share button getting cutoff in send successful modal

src/components/RKSignersModal.tsx, src/screens/QRScreens/ShowQR.tsx, src/screens/QRScreens/SignWithChannel.tsx, src/screens/Send/SendConfirmation.tsx, src/screens/SignTransaction/SignWithQR.tsx, src/screens/SignTransaction/SignerModals.tsx, src/screens/Vault/SignerAdvanceSettings.tsx, src/utils/utilities.ts
=> Jade Remote Key Share and Sign

src/components/MenuCard.tsx, src/components/OptionCard.tsx, src/components/UAIEmptyState.tsx, src/components/XPub/TransferPolicy.tsx, src/screens/AddWalletScreen/AddWallet.tsx, src/screens/AddWalletScreen/ImportWallets.tsx, src/screens/AppSettings/TorSettings.tsx, src/screens/Home/components/HeaderDetails/components/UAIView.tsx, src/screens/SigningDevices/ManageSigners.tsx, src/screens/SigningDevices/SignerSettings.tsx, src/screens/Vault/AssignSignerType.tsx, src/screens/Vault/SignerAdvanceSettings.tsx, src/screens/Vault/SigningDeviceIcons.tsx, src/screens/Vault/VaultDetails.tsx, src/screens/Vault/VaultSettings.tsx, src/screens/Vault/components/AssignSignerTypeCard.tsx, src/screens/Vault/components/UnknownSignerInfo.tsx, src/screens/ViewTransactions/TransactionDetails.tsx, src/screens/WalletDetails/WalletDetails.tsx, src/screens/WalletDetails/WalletDetailsSettings.tsx, src/screens/WalletDetails/WalletSettings.tsx
=> font and ui improvements in the app

src/components/RKSignersModal.tsx, src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/navigation/Navigator.tsx, src/navigation/types.ts, src/screens/QRScreens/ShowPSBT.tsx, src/screens/QRScreens/ShowQR.tsx, src/screens/QRScreens/SignWithChannel.tsx, src/screens/Send/AmountDetails.tsx, src/screens/Send/PSBTSendConfirmation.tsx, src/screens/Send/ReceiptWrapper.tsx, src/screens/Send/TransferCard.tsx, src/screens/SignTransaction/SignWithQR.tsx, src/screens/Vault/SignerAdvanceSettings.tsx, src/screens/ViewTransactions/TransactionAdvancedDetails.tsx, src/utils/utilities.ts
=>  Show Transaction details for Remote and Mobile Key

src/components/Carousel/ChoosePlanCarousel.tsx, src/components/KeeperHeader.tsx, src/screens/ChoosePlanScreen/components/PlanDetailsCards.tsx, src/screens/InheritanceToolsAndTips/BackupRecovery.tsx, src/screens/InheritanceToolsAndTips/KeySecurity.tsx, src/screens/Recieve/ReceiveScreen.tsx, src/screens/Vault/AddSigningDevice.tsx, src/screens/Vault/SigningDeviceDetails.tsx
=> fixes various ui issues

src/screens/Recieve/ReceiveScreen.tsx
=> Fix the receive address page input size beyond address 10

src/components/AppNumPad/KeyPadButton.tsx, src/components/AppNumPad/KeyPadView.tsx, src/components/AppPinInput/PinDotView.tsx, src/components/Dot.tsx, src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/screens/LoginScreen/CreatePin.tsx, src/screens/LoginScreen/Login.tsx
=> Redesigns login and create pin screens

src/components/RKSignersModal.tsx, src/screens/SignTransaction/SignerModals.tsx, src/screens/SigningDevices/SetupTapsigner.tsx, src/screens/Vault/SignerAdvanceSettings.tsx, src/utils/utilities.ts
addressing #5616
Enable Key Share&Sign Specter #5641
=> TapSigner & SeedSigner Remote sharing and signing

src/screens/LoginScreen/CreatePin.tsx
=> fixes create passcode input issue

src/store/sagas/concierge.ts
=> fixes Need Help redirection in Recovery Flow 

src/navigation/Navigator.tsx
=> Fixes flash in dark mode android #5047

src/components/Carousel/ChoosePlanCarouselItem.tsx, src/screens/ChoosePlanScreen/ChoosePlan.tsx, src/utils/utilities.ts
Addressing Show per month price in Yearly subscriptions #5659
=> Fixes yearly subscription prices by month

src/screens/Recieve/ReceiveScreen.tsx, src/screens/Vault/SignerAdvanceSettings.tsx, src/services/wallets/operations/index.ts, src/utils/service-utilities/utils.ts, src/utils/utilities.ts
Addressing #5645 
Added key sharing and signing for passport
=> Fixes enable key sharing and signing for Ledger/Trezor/Bitbox 

src/screens/AppSettings/PrivacyAndDisplay.tsx, src/screens/Home/InititalAppController.tsx, src/screens/LoginScreen/CreatePin.tsx, src/services/sentry/index.ts, src/storage/realm/RealmProvider.tsx, src/utils/service-utilities/config.ts
Addressing Share Analytics umbrella issue #5055
=> Enable sentry only for Development 

src/screens/InheritanceToolsAndTips/components/LetterOfAttorney.tsx, src/utils/GenerateLetterToAtternyPDFInheritanceTool.ts
=> Add all signers to LoA

src/screens/Vault/SignerAdvanceSettings.tsx, src/utils/utilities.ts
Addressing Changes required in Vault Detection from PSBT logic #5668
=> updates Vault Detection For MiniScript Support

src/screens/Send/AddSendAmount.tsx, src/screens/Send/SendConfirmation.tsx, src/screens/Send/SendScreen.tsx, src/screens/Vault/VaultMigrationController.tsx, src/services/wallets/operations/index.ts, src/store/sagas/uai.ts
=> Allow sending unconfrimed balances

src/services/wallets/operations/utils.ts
Refactor script satisfier to improve signature handling and key mapping.
=> Improves: Script Satisfier for Miniscript Vault w/ Probabilities

src/screens/Vault/VaultMigrationController.tsx
Addresses: Simultaneous archiving of both the new and old vaults during the vault migration process(update scheme/revaulting) as they have the same configuration(including the MS-IK timeline).
Adds check for an existing vault w/ exact configuration, including ms-scheme, prior to initiating migration.
=> fixes: simultaneous archive during vault migration

src/screens/AppSettings/ManageWallets.tsx, src/utils/service-utilities/utils.ts
Fix import of Miniscript vault, also fix issue entering the import vault page after deleting a vault
=> Fix import of Miniscript vault

src/screens/Send/PriorityModal.tsx
Fixes issues with stats string conversion to 8 precision points.
=> Fixes stats format in Priority modal

src/utils/GenerateAllVaultsFilePDF.ts
=> fixes each config not displaying on separate page

src/components/Modal/WalletVaultCreationModal.tsx, src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/screens/SigningDevices/SetupCollaborativeWallet.tsx
=> fixes content in collab vault

src/screens/Vault/AddSigningDevice.tsx, src/screens/Vault/CreateReserveKeyVault.tsx, src/screens/Vault/ResetInheritanceKey.tsx, src/screens/Vault/VaultMigrationController.tsx, src/services/wallets/factories/VaultFactory.ts, src/services/wallets/operations/miniscript/policy-generator.ts, src/services/wallets/operations/utils.ts, src/store/sagas/wallets.ts
Addresses:
- https://github.com/bithyve/bitcoin-keeper/issues/5720
- https://github.com/bithyve/bitcoin-keeper/issues/5730
=> Miniscript updates: adds multipath to revaulting and fixes update-scheme flow

src/screens/SignTransaction/SignTransactionScreen.tsx, src/screens/SignTransaction/SignerList.tsx
=> updates and fixes ui of sign transaction screen

src/store/sagas/send_and_receive.ts
fixes tnx failure due to missing recipients in case of custom priority
=> Fixes tnx failure issue 

src/screens/Vault/VaultMigrationController.tsx, src/services/wallets/factories/VaultFactory.ts, src/services/wallets/operations/miniscript/policy-generator.ts
=> MS-IK: Multipath fix for Update-Scheme

src/assets/images/upload-black.svg, src/components/TabBar.tsx, src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/screens/Vault/GenerateVaultDescriptor.tsx, src/screens/Vault/VaultSettings.tsx
=> updates ui for MS-IK vault config

src/screens/Home/InititalAppController.tsx, src/screens/Vault/SigningDeviceDetails.tsx, src/utils/service-utilities/utils.ts
Addressing 
Missing Vault detection for Remote key signing using deep link #5757
=> fixes Rk link vault detection 

src/components/MessagePreview.tsx, src/screens/Home/InititalAppController.tsx, src/screens/SigningDevices/RemoteSharing.tsx
Addressing 
Remove tier restriction on remote key link sharing #5770
=> Removes tier restriction on remote key link sharing 

src/screens/SignTransaction/SignTransactionScreen.tsx, src/screens/SignTransaction/SignerModals.tsx, src/services/qr/index.ts, src/store/sagas/uai.ts
=> Allow signing with unknown signer

src/screens/Vault/HardwareModalMap.tsx
=> fixes ui breaking on setup SS modal

src/hooks/useNotificationHandler.tsx, src/screens/SigningDevices/ManageSigners.tsx
Addressing 
Remote Share: Showing wrong modal on key acceptance/rejection. #5783
=> Fixes remote link sharing modal 

src/screens/SigningDevices/ManageSigners.tsx, src/screens/SigningDevices/SetupCollaborativeWallet.tsx
=> Fix UI issues

src/screens/SigningDevices/SetupCollaborativeWallet.tsx, src/store/sagas/wallets.ts
Elevates the restriction on details sharing(contact) post joining a collab session.
=> Collab-session: simultaneous cosigner addition

src/screens/Vault/GenerateVaultDescriptor.tsx
=> Fix vault config animated QR

src/screens/Home/components/DowngradeModal.tsx, src/store/sagas/login.ts
Addressing
Subscription expiration issue #4524
=> fixes Subscription expiration issue 

src/hardware/keystone/index.ts
Addressing 
Multiple keystone getting created when importing vault #5818
=> fixes keystone signer id case

src/components/SetupSignerOptions.tsx, src/screens/Vault/HardwareModalMap.tsx
=> updates ui for setup signer options

src/utils/service-utilities/utils.ts
=> Add checksum when exporting descriptor

src/screens/Send/AddSendAmount.tsx, src/screens/Send/SendScreen.tsx
=> fixes showing selected utxo amount

src/components/Modal/ConciergeOnboardingModal.tsx, src/screens/AddWalletScreen/AddWallet.tsx, src/screens/CloudBackup/CloudBackupScreen.tsx, src/screens/EnterWalletDetailScreen/EnterWalletDetailScreen.tsx, src/screens/Home/HomeScreen.tsx, src/screens/ImportWalletScreen/ImportWalletScreen.tsx, src/screens/InheritanceToolsAndTips/InheritanceToolsAndTips.tsx, src/screens/KeeperConcierge/CreateTicket.tsx, src/screens/KeeperConcierge/TechnicalSupport.tsx, src/screens/KeeperConcierge/TicketDetails.tsx, src/screens/KeeperConcierge/components/CreateTicketCTA.tsx, src/screens/KeeperConcierge/components/TicketHistory.tsx, src/screens/QRScreens/ScanQR.tsx, src/screens/Recovery/EnterSeedScreen.tsx, src/screens/SigningDevices/ManageSigners.tsx, src/screens/SigningDevices/components/CollaborativeModals.tsx, src/screens/Vault/SignerCategoryList.tsx, src/screens/Vault/SigningDeviceDetails.tsx, src/screens/Vault/SigningDeviceList.tsx, src/screens/Vault/VaultConfigurationRecreation.tsx, src/screens/Vault/VaultDetails.tsx, src/screens/Vault/VaultSetup.tsx, src/screens/WalletDetails/components/LearnMoreModal.tsx, src/services/backend/Zendesk.ts
Addressing 
Concierge - Technical support: Content and UI change. #5835
=> updates concierge flow

src/screens/ChoosePlanScreen/ChoosePlan.tsx, src/screens/ChoosePlanScreen/TierUpgradeModal.tsx
Addressing 
Incorrect Subscription Messages . #5823
=> fixes Incorrect Subscription Messages

patches/react-native-tcp-socket+5.6.2.patch, src/screens/KeeperConcierge/CreateTicket.tsx, src/screens/SigningDevices/SetupPortal.tsx, src/services/backend/Relay.ts, src/utils/service-utilities/utils.ts
Fixes new plan purchase on android production environment. #5854
Updated concierge wallet attributes format.
Disable checksum in vault descriptor for portal.
Fixes app crash on node disconnect. #5840
=> Fixes minor issues 

src/storage/realm/migrations.ts
=> Fix issue with migration

ios/Podfile.lock, package.json, src/components/Buttons.tsx, src/components/RKSignersModal.tsx, src/screens/Channel/ConnectChannel.tsx, src/screens/Home/InititalAppController.tsx, src/screens/QRScreens/DisplayQR.tsx, src/screens/QRScreens/RegisterWithChannel.tsx, src/screens/QRScreens/RegisterWithQR.tsx, src/screens/QRScreens/SignWithChannel.tsx, src/screens/Recieve/ReceiveScreen.tsx, src/screens/Send/AddSendAmount.tsx, src/screens/Send/PSBTSendConfirmation.tsx, src/screens/Send/SendConfirmation.tsx, src/screens/SignTransaction/SignTransactionScreen.tsx, src/screens/SignTransaction/SignerModals.tsx, src/screens/SigningDevices/SetupAssistedVault.tsx, src/screens/Vault/AddReserveKey.tsx, src/screens/Vault/GenerateVaultDescriptor.tsx, src/screens/Vault/ResetInheritanceKey.tsx, src/screens/Vault/SignerAdvanceSettings.tsx, src/screens/Vault/SigningDeviceDetails.tsx, src/screens/Vault/VaultConfigurationRecreation.tsx, src/screens/Vault/VaultMigrationController.tsx, src/services/wallets/operations/utils.ts, yarn.lock
- Issue when the mobile device turns off during channel connection
- Make Jade wallet registration only via USB for Miniscript
- Fix file name when exporting vault
- Jade and other none Coldcard QRs not working
- Addresses #5710
=> Fix issues with using HWWs

src/screens/Recovery/EnterSeedScreen.tsx
=> Fixes restore seed key issue 

src/screens/AppSettings/Node/NodeSelection.tsx, src/screens/AppSettings/Node/NodeSettings.tsx, src/screens/Vault/HardwareModalMap.tsx, src/store/sagas/bhr.ts
Addressing #5884 
Clears Signing server OTP field on submit.
=> Node backup and restore

src/components/Switch/Switch.tsx, src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/hooks/useSettingKeeper.tsx, src/screens/Home/components/Settings/Component/SettingCard.tsx, src/screens/Home/components/Settings/keeperSettings.tsx
=> cloud backup option in setting screen

src/components/CTACardDotted.tsx, src/components/MenuFooter.tsx, src/screens/AddWalletScreen/ConfirmWalletDetails.tsx, src/screens/CloudBackup/CloudBackupScreen.tsx, src/screens/Home/HomeScreen.tsx, src/screens/Home/components/Settings/AppSettings.tsx, src/screens/Home/components/Settings/InheritanceDocumentScreen.tsx, src/screens/Home/components/Wallet/WalletCard.tsx, src/screens/InheritanceToolsAndTips/InheritanceToolsAndTips.tsx, src/screens/KeeperConcierge/CreateTicket.tsx, src/screens/KeeperConcierge/KeeperConcierge.tsx, src/screens/KeeperConcierge/TechnicalSupport.tsx, src/screens/KeeperConcierge/components/ConciergeScreenWrapper.tsx, src/screens/KeeperConcierge/components/CreateTicketCTA.tsx, src/screens/KeeperConcierge/components/TicketHistory.tsx, src/screens/QRScreens/ScanQR.tsx, src/screens/Recovery/EnterSeedScreen.tsx, src/screens/SigningDevices/ManageSigners.tsx, src/screens/SigningDevices/components/CollaborativeModals.tsx, src/screens/Vault/SignerCategoryList.tsx, src/screens/Vault/SigningDeviceDetails.tsx, src/screens/Vault/SigningDeviceList.tsx, src/screens/Vault/VaultConfigurationRecreation.tsx, src/screens/Vault/VaultDetails.tsx, src/screens/WalletDetails/components/LearnMoreModal.tsx
=> concierge flow new ui

src/screens/Vault/AssignSignerType.tsx, src/screens/Vault/VaultSettings.tsx, src/screens/Vault/components/AssignSignerTypeCard.tsx
Addressing 
Change signer type: App Crashes When Changing Signer Type . #5911
=> Fixes change signer type 

src/screens/KeeperConcierge/CreateTicket.tsx, src/screens/NewKeeperAppScreen/NewKeeperAppScreen.tsx, src/screens/Recovery/EnterSeedScreen.tsx, src/services/backend/Relay.ts, src/store/reducers/bhr.ts, src/store/sagas/bhr.ts
Addressing 
On Revault/UpdateScheme failure, vault is lost. #5922 
No Success Message Displayed After Ticket Creation on Support Page. #5924
Adds Not internet modal while App recovery.
=> Minor fixes 

src/screens/Home/Notifications/NotificationsCenter.tsx, src/services/backend/Zendesk.ts
Hide concierge notifications after actioned.
Add environment field when creating zendesk ticket
=> Fix concierge issues 

ios/Podfile.lock, package.json, yarn.lock
Updated React native reanimated version to 3.8.1 due to android release failure.
Added react-dom as dev dependency.
=> fix: ReanimatedVersion/ DomDependency

src/components/HomeScreenHeader.tsx, src/screens/AddSigner/SignerCard.tsx, src/screens/Home/components/Keys/SignerList.tsx, src/screens/LoginScreen/CreatePin.tsx
=> fix faq button and home screen header

src/components/Backup/BackupHealthCheckList.tsx
=> fix recovery footer

src/screens/ChoosePlanScreen/ChoosePlan.tsx
Addressing
Subscription: Getting error on upgrade. #5964
=> fix: finishSubsHandler

src/screens/Home/components/Settings/Component/SettingCard.tsx
Fixes issues with settings screen toggle not visible
=> fix: SettingsToggleOptions

src/hooks/useWalletAsset.ts, src/screens/AddSigner/SignerCard.tsx, src/screens/Home/components/Keys/SignerList.tsx, src/screens/KeeperConcierge/components/CreateTicketCTA.tsx
=> fix canary tag and concierge screen button

src/hooks/useSettingKeeper.tsx
fixes multiple backup api calls on toggle change from settings screen
=> fix: CloudBackupMultipleCalls

android/app/build.gradle, ios/hexa_keeper.xcodeproj/project.pbxproj, ios/hexa_keeper/Info.plist, ios/hexa_keeperTests/Info.plist, ios/hexa_keeper_dev-Info.plist
=> release 463

src/screens/WalletDetails/WalletSettings.tsx
=> fix transfer policy ui glitch

src/storage/realm/realm.ts
=> fixes realm error 

src/services/backend/Zendesk.ts
Onboarding call tickets for prod to assign automatically and set status to open.
=> Upt Onboarding call params

src/screens/SignTransaction/SignWithQR.tsx
=> Fix sign tx with Specter DIY

src/screens/SigningDevices/SetupColdCard.tsx, src/screens/Vault/HardwareModalMap.tsx, src/services/nfc/index.ts
=> Fix Coldcard NFC communication

src/store/sagas/bhr.ts
=> Disable subscriptions restore on app restore.

src/screens/NFCChannel/ShareWithNfc.tsx, src/screens/QRScreens/RegisterWithQR.tsx
- Fix cleanup NFC modal on android after writing data
- Fix specter wallet registration for normal multisig
=> Cleanup NFC modal on android after writing data

src/screens/ChoosePlanScreen/ChoosePlan.tsx, src/screens/LoginScreen/Login.tsx, src/store/reducers/settings.ts, src/store/sagas/login.ts
=> Discard no internet modal on Pleb login  

src/store/sagas/login.ts
fixes issue with electrum node not connecting after api calls to relay fails due to tor connect.
=> Fix node connection due to relay fail on tor.

src/components/Modal/WalletVaultCreationModal.tsx, src/hooks/useWalletAsset.ts, src/screens/AddWalletScreen/ConfirmWalletDetails.tsx, src/screens/Home/components/Wallet/WalletCard.tsx
=> fix pills colors

src/services/backend/Relay.ts, src/store/sagas/bhr.ts
=> fixes unencrypted vault.scheme storage

App.tsx, android/build.gradle, ios/Podfile, ios/Podfile.lock, package.json, src/screens/KeeperConcierge/KeeperConcierge.tsx, src/store/sagaActions/concierge.ts, src/store/sagas/concierge.ts, src/store/sagas/index.ts, yarn.lock
Removes zendesk Messaging integration. 
fixes issues with android release due to restricted permissions.
=> fix: remove ZendeskMessaging integration

src/screens/UTXOManagement/UTXOManagement.tsx, src/services/wallets/operations/index.ts
Remove used unconfirmed UTXOs also on mainnet
=> Remove used unconfirmed UTXOs

src/services/wallets/operations/index.ts, src/store/sagas/send_and_receive.ts, src/store/sagas/wallets.ts
=> Update change labels

src/models/interfaces/AssistedKeys.ts, src/screens/SignTransaction/SignTransactionScreen.tsx, src/screens/SignTransaction/signWithSD.ts, src/screens/Vault/ChoosePolicyNew.tsx, src/screens/Vault/SignerAdvanceSettings.tsx, src/screens/Vault/SigningRequest.tsx, src/screens/Vault/components/SigningRequestCard.tsx, src/services/backend/SigningServer.ts, src/store/reducers/storage.ts, src/store/sagaActions/storage.ts, src/store/sagas/index.ts, src/store/sagas/login.ts, src/store/sagas/storage.ts
Integrates pull-based delayed transactions.
=> Server Key: Delayed Transaction integration

src/hooks/useConfigReocvery.tsx, src/navigation/types.ts, src/screens/AddWalletScreen/ConfirmWalletDetails.tsx, src/screens/Home/components/Wallet/HomeWallet.tsx, src/screens/Send/SendConfirmation.tsx, src/screens/SignTransaction/SignTransactionScreen.tsx, src/screens/UTXOManagement/UTXOManagement.tsx, src/screens/Vault/VaultDetails.tsx, src/screens/Vault/components/TransactionsAndUTXOs.tsx, src/screens/ViewTransactions/TransactionDetails.tsx, src/screens/WalletDetails/WalletDetails.tsx, src/services/electrum/client.ts, src/services/wallets/operations/index.ts, src/services/wallets/operations/utils.ts, src/store/sagas/wallets.ts, src/utils/service-utilities/config.ts
Improve wallet to fully sync properly and add a soft refresh for initial loading
=> Improve wallets sync

src/screens/Vault/SignerAdvanceSettings.tsx, src/screens/Vault/SigningRequest.tsx
Fixes issues in Server Key settings and remove old Inheritance Server code
=> Fix server key settings page

src/services/backend/SigningServer.ts, src/store/sagas/upgrade.ts
Addresses https://github.com/bithyve/bitcoin-keeper/issues/6113
=> Migration saga: server key policy

src/screens/AppSettings/Node/AddNode.tsx, src/screens/AppSettings/Node/NodeSelection.tsx, src/services/electrum/client.ts, src/services/electrum/node.tsx, tests/electrum-client/client.test.js
Show electrum connection error and increase timeout to 20 seconds
Addresses #6105
=> Show electrum connection error

src/components/SegmentController.tsx, src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/hardware/index.ts, src/hardware/jade/index.ts, src/hardware/passport/index.ts, src/hardware/seedsigner/index.ts, src/hardware/signerSetup.ts, src/navigation/Navigator.tsx, src/navigation/types.ts, src/screens/AddSigner/AddMultipleXpub.tsx, src/screens/SignTransaction/SignWithQR.tsx, src/screens/Vault/HardwareModalMap.tsx
=> Adds multiple xpubs support

src/models/interfaces/AssistedKeys.ts, src/screens/Vault/ChoosePolicyNew.tsx, src/services/backend/SigningServer.ts, src/store/reducers/storage.ts, src/store/sagaActions/storage.ts, src/store/sagaActions/wallets.ts, src/store/sagas/index.ts, src/store/sagas/login.ts, src/store/sagas/storage.ts, src/store/sagas/wallets.ts
Addresses https://github.com/bithyve/bitcoin-keeper/issues/6070
=> Server Key: Delayed Policy Update

src/hardware/portal/index.ts, src/screens/AddSigner/AddMultipleXpub.tsx, src/screens/SigningDevices/SetupPortal.tsx
=> Portal multiple xpub support 

src/screens/LoginScreen/Login.tsx, src/store/reducers/storage.ts, src/store/sagas/login.ts
Restore subscription on login after downgraded to pleb due to network issue
Adressing #6114
=> Restore subscription on login

src/constants/defaultData.tsx, src/screens/ChoosePlanScreen/ChoosePlan.tsx
=> Fix free trial text

src/screens/Send/SendConfirmation.tsx
=> Server Key: Cached transaction & Signing Request Sync

src/models/interfaces/AssistedKeys.ts, src/screens/SignTransaction/signWithSD.ts, src/screens/Vault/SigningRequest.tsx, src/services/backend/SigningServer.ts, src/services/wallets/interfaces/index.ts, src/services/wallets/operations/index.ts
Corresponds to https://github.com/bithyve/SigningServer/pull/141
Addresses https://github.com/bithyve/bitcoin-keeper/issues/6115
=> Server Key: Derive subpath from PSBT

src/store/sagas/bhr.ts, src/store/sagas/wallets.ts
=> fix: recreateWalletOnEmptyBackup

src/hardware/index.ts, src/screens/Vault/AddSigningDevice.tsx, src/screens/Vault/components/AssignSignerTypeCard.tsx, src/services/wallets/interfaces/vault.ts, src/storage/realm/realm.ts, src/storage/realm/schema/vault.ts
Addresses https://github.com/bithyve/bitcoin-keeper/issues/6224 and https://github.com/bithyve/bitcoin-keeper/issues/6226
=> Server Key: Unknown Signer support

android/app/build.gradle, ios/hexa_keeper.xcodeproj/project.pbxproj, ios/hexa_keeper/Info.plist, ios/hexa_keeperTests/Info.plist, ios/hexa_keeper_dev-Info.plist
Various UI updates
Bug fixes and performance improvements
=> Release 2.1.1

src/screens/ChoosePlanScreen/ChoosePlan.tsx, src/screens/ChoosePlanScreen/components/SubscriptionList.tsx
=> fixes Subscription List Without Play Services

src/navigation/AppStateHandler.tsx, src/navigation/Navigator.tsx, src/screens/Home/InititalAppController.tsx, src/store/reducers/login.ts
=> Feat: login check

src/hooks/useUaiStack.ts, src/store/sagas/bhr.ts, src/store/sagas/login.ts, src/store/sagas/uai.ts
Addressing #6282 
Also removes default uai for notifications as its no longer needed.
=> fix: vaultNotificationOnRestore/ RemovedDefaultNotification

android/app/build.gradle, ios/hexa_keeper.xcodeproj/project.pbxproj, ios/hexa_keeper/Info.plist, ios/hexa_keeperTests/Info.plist, ios/hexa_keeper_dev-Info.plist
Release 494
Fixes Keeper private app icon reference issue in info.plist.
=> release494/ fix iOSAppIconInfo.plist issue

src/screens/KeeperConcierge/CreateTicket.tsx, src/screens/KeeperConcierge/TicketDetails.tsx, src/screens/KeeperConcierge/components/CTAFooter.tsx, src/screens/KeeperConcierge/components/CreateTicketCTA.tsx, src/screens/KeeperConcierge/components/ImagePreview.tsx, src/screens/KeeperConcierge/components/TicketItem.tsx, src/screens/KeeperConcierge/components/TicketList.tsx, src/services/backend/Zendesk.ts
Addressing https://github.com/bithyve/bitcoin-keeper/issues/6322
Handle multiple images in concierge ticket, limited to 5 images. 
View multiple images in ticket response view
=> feat: ConciergeMultipleImageSupport

src/services/backend/SigningServer.ts
Corresponds to https://github.com/bithyve/SigningServer/pull/164/commits/cef571fdaa9913d504c3e2b39f4c0aaba7adb34b
=> Fix: Validation flag for Server Key

src/hardware/index.ts, src/screens/Vault/AssignSignerType.tsx
- Refactors status method for Server Key
- Fixes type Assignment for Imported Server Key https://github.com/bithyve/bitcoin-keeper/issues/6385
=> Server key updates

src/hardware/index.ts
fixes Jade network mode while addition when Bitcoin network mode is set to testnet
=> fix: NetworkModeInTestNetForJadeAddition

src/context/Localization/language/en.json, src/context/Localization/language/es.json
=> Fix choose quorum text

src/context/Localization/language/en.json, src/context/Localization/language/es.json
Changes to Inheritance documents upgrade tier message as per figma UI.
=> fix: InheritanceDocTierUpgradeMessage

src/screens/Vault/components/AssignSignerTypeCard.tsx
Addresses https://github.com/bithyve/bitcoin-keeper/issues/6461
=> Fix: Assign server key via Keys flow

src/screens/KeeperConcierge/CreateTicket.tsx
Addressing https://github.com/bithyve/bitcoin-keeper/issues/6189
=> Updated Concierge Shared Attributes

src/screens/AppSettings/Node/NodeSettings.tsx, src/store/reducers/account.ts, src/store/sagas/bhr.ts, src/store/sagas/login.ts, src/store/sagas/settings.ts, src/store/sagas/storage.ts
Fixed default vault/key creation for multi user flow 
Clears concierge details on multi user app recovery flow 
Fixed loader even after node connected successfully.
=> fix multi user issue

android/app/build.gradle, ios/hexa_keeper.xcodeproj/project.pbxproj, ios/hexa_keeper/Info.plist, ios/hexa_keeperTests/Info.plist, ios/hexa_keeper_dev-Info.plist, package.json, src/screens/Send/SendConfirmation.tsx, src/utils/service-utilities/utils.ts
Added Multi User Mode
Added Timelock option to enhanced wallets
Added option to save external seed words as a hot key
UI updates and bug fixes
=> Release 2.3.0

src/screens/Home/InititalAppController.tsx, src/store/reducers/settings.ts
Addressing https://github.com/bithyve/bitcoin-keeper/issues/6568
=> feat: AppWideLoaderForMagicLink

src/components/KeeperHeader.tsx, src/components/ThemedSvg.tsx/ThemedIcons.js, src/components/TransactionElement.tsx, src/screens/AddSigner/SignerCard.tsx, src/screens/AddWalletScreen/ConfirmWalletDetails.tsx, src/screens/Send/AddSendAmount.tsx, src/screens/SigningDevices/ManageSigners.tsx, src/screens/SigningDevices/SetupSeedWordSigner.tsx, src/screens/Vault/SelectInitialTimelock.tsx, src/screens/WalletDetails/CosignerDetails.tsx
=> fix multiple issues

src/components/KeeperHeader.tsx, src/components/ThemedSvg.tsx/ThemedIcons.js, src/components/TransactionElement.tsx, src/screens/AddSigner/SignerCard.tsx, src/screens/AddWalletScreen/ConfirmWalletDetails.tsx, src/screens/Send/AddSendAmount.tsx, src/screens/SigningDevices/ManageSigners.tsx, src/screens/SigningDevices/SetupSeedWordSigner.tsx, src/screens/Vault/SelectInitialTimelock.tsx, src/screens/WalletDetails/CosignerDetails.tsx
Reverts bithyve/bitcoin-keeper#6565
=> Revert "fix multiple issues"

src/screens/Recovery/EnterSeedScreen.tsx, src/store/sagaActions/wallets.ts, src/store/sagas/index.ts, src/store/sagas/wallets.ts
=> RememberSeedOnHealthCheck and updateVaultSigner

src/screens/SignTransaction/SignerModals.tsx
Addressing https://github.com/bithyve/bitcoin-keeper/issues/6532
=> Fixes unknown signer signing flow  

src/screens/FeeInsights/FeeDataStats.tsx, src/screens/FeeInsights/FeeGraph.tsx, src/utils/utilities.ts
Addressing https://github.com/bithyve/bitcoin-keeper/issues/6580
fixes multiple data points for a single day.
=> improves fee graph 

src/hardware/seedsigner/index.ts
=> Fix issue with seedsigner PSBT

src/screens/Home/InititalAppController.tsx
=> Fixes signer detection in magic link

src/screens/SignTransaction/SignTransactionScreen.tsx, src/screens/Vault/VaultDetails.tsx, src/store/reducers/cachedTxn.ts, src/store/sagaActions/send_and_receive.ts, src/store/sagas/index.ts, src/store/sagas/send_and_receive.ts, src/utils/utilities.ts
Addressing https://github.com/bithyve/bitcoin-keeper/issues/6598
=> Discard broadcasted cached tnx 

src/screens/SignTransaction/SignerModals.tsx
Addressing https://github.com/bithyve/bitcoin-keeper/issues/6604
=> fix: OtherSignerSigningFlow

src/components/MenuFooter.tsx, src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/screens/Home/HomeScreen.tsx, src/screens/Home/components/buyBtc/BtcGraph.tsx, src/screens/Home/components/buyBtc/BuyBtc.tsx, src/utils/utilities.ts
Ui changes for Bitcoin graph 
Fix app crash on buy with wallet selection
=> Buy Tab changes 

android/build.gradle
Upgrades 
Android target api to 35
Android build gradle to 8.8.0
=> Android targetSdk upgrade

src/screens/Home/components/Keys/SignerList.tsx, src/screens/SigningDevices/ManageSigners.tsx, src/screens/Vault/VaultDetails.tsx
Addressing Health Check Indicator Missing in "Keys" Tab. #6621
Gear icon in top-right corner of Vault UI appears too large. #6630
=> fixes minor ui issues 

src/screens/Vault/SigningDeviceDetails.tsx, src/store/sagas/bhr.ts
Addressing Red Dot Indicator Persists After Successful Key Health Check. #6648
=> Fixes UAI dismiss on HC

src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/screens/Recovery/EnterSeedScreen.tsx
Addressing 
Need the correct USDT Wallet import context #6688
=> feat: ImportUsdtInfoModal

src/context/Localization/language/en.json, src/context/Localization/language/es.json, src/screens/Send/SendConfirmation.tsx, src/screens/SignTransaction/SignTransactionScreen.tsx
Addressing https://github.com/bithyve/bitcoin-keeper/issues/6680
=> fixes missing tnx url in share

src/hooks/useUSDTWallets.ts
Addresses https://github.com/bithyve/bitcoin-keeper/issues/6703
=> Improves: USDT Wallets' Instance Gen 

ios/Podfile.lock, package.json, yarn.lock
Bump-up react-native-screens to 3.34.0
=> fix android emulator crash

src/hooks/useUSDTWallets.ts
Addresses https://github.com/bithyve/bitcoin-keeper/issues/6714
=> USDT wallets: n/w filter

src/services/wallets/factories/USDTWalletFactory.ts, src/services/wallets/operations/dollars/USDT.ts
Addresses https://github.com/bithyve/bitcoin-keeper/issues/6722
=> Imported USDT Wallet: GasFree Fees Transaction removal

android/app/src/main/res/xml/network_security_config.xml, src/screens/BuyBitcoin/BuyBitcoinScreen.tsx, src/screens/USDT/BuyUstd.tsx, src/utils/service-utilities/config.ts
Addressing Update Ramp urls #6675
Dependencies
=> Updates ramp url 

src/components/KeeperModal.tsx, src/screens/Home/components/buyBtc/Swap/Swaps.tsx
=> fix swap issue

src/screens/SigningDevices/SetupOtherSDScreen.tsx, src/screens/Vault/HardwareModalMap.tsx
Addressing 
https://github.com/bithyve/bitcoin-keeper/issues/6776#issue-3273167645
=> fixes Other Signer HC Flow

src/screens/Home/components/Contact/component/Contact.tsx
Addressing
https://github.com/bithyve/bitcoin-keeper/issues/6802
=> Enabled Contact Add By Text
