- src/screens/Send/UTXOSelection.tsx
Issue source: BTC value was being passed as the amount for recipient's output utxo on the UTXO selection screen
Fix: Passed in the amount in Sats
Addresses #3336
> Coin control: Selection based tx fix

- src/core/wallets/operations/index.ts
- src/core/wallets/operations/utils.ts
Issue: fingerprint generation via mnemonic leads to significant delay while adding inputs
Fix: use the cached fingerprint while adding inputs to PSBT
Partially addresses #3330
> PSBT::addInput - use cached mfp

- src/screens/WalletDetails/components/RampModal.tsx
Buy with Ramp isn't working in UK due to some policy changes. So we're processing buy requests with a [vanila link](https://ramp.network/buy#). This is a temporary fix, we may remove it in the future once it starts working again.
> Buy with ramp for UK #3940

- src/screens/AppSettings/ManageWallets.tsx
Fixes #4067
Immutable wallet objects were being passed to sagas which was causing them to fail due to intermediary shadow objects in the reducer(here, txnPrerequisites, leading to missing inputs).
> Manage Wallets: Move funds fix

- src/screens/EnterWalletDetailScreen/EnterWalletDetailScreen.tsx
Fix for new wallet creation without 'Auto Transfer' value.  If the transfer policy is empty it results in parseInt failing with 'NaN'. Added a check for the same.
> Create New wallet without the 'Auto Transfer' value

- ios/Podfile.lock
- package.json
- yarn.lock
Addresses #https://github.com/bithyve/bitcoin-keeper/security/dependabot/63
> Bump react-native-mmkv from 2.6.3 to 2.11.0

- src/screens/Vault/SignerAdvanceSettings.tsx
If the signer is a single sig, canary wallet should not be allowed. 
#4336
> canary wallet restriction based on single sig

- src/services/wallets/operations/index.ts
acknowledges: https://github.com/bithyve/bitcoin-keeper/issues/4354
* Checks and updates PSBT for tapsigner only if signatures are available
> Fix PSBT signature addition in WalletOperations

- ios/hexa_keeper/Info.plist
- ios/hexa_keeper_dev-Info.plist
* iOS doesn't let you install the app if UIRequiredDeviceCapabilities has NFC.
* Removed the required compatibility check
> Remove NFC device requirement from Info.plist

- src/hooks/useTestSats.tsx
- src/services/backend/Relay.ts
Hands over the quantity decision to backend. Simplifies funding changes based on fee variation on testnet.
Partly addresses #4392 and improves upon #4396
> Testnet sats: moved to backend(amt)

- src/hooks/useVault.ts
Canary Waalet hidden at UI level for all vaults 
https://github.com/bithyve/bitcoin-keeper/issues/4388
> Canary Vault Filter at all vault UI

- src/components/TransactionElement.tsx
Addresses: 
#4662
fixes pending icon showing on cached transactions
> fixes pending icon showing on cached transactions

- src/context/Localization/language/en.json
- src/context/Localization/language/es.json
Fixes a missing comma (,) that occurred during a merge conflict resolution, which led to a JavaScript bundle failure.
> fix: missing comma in localization file

- ios/hexa_keeper/hexa_keeper.entitlements
removed Ndef from ios prod entitlements to fix issue with uploading ipa to testlight.
> fix: removed NDEF from prod entitlements ios

- src/screens/Send/SendScreen.tsx
> disabled send to your own wallets if there is only one wallet available

- src/services/wallets/operations/miniscript/default/InheritanceVault.ts
- src/services/wallets/operations/miniscript/policy-generator.ts
This pull request enhances the Miniscript policy generation by introducing a probability parameter for each phase. Key changes include:
- Adding a probability field to the Phase interface.
- Modifying generateInheritanceVaultElements to include probability values.
- Updating policy-generator(introducing or fragment) to use the probability values for optimizing script generation.
> Add: Relative Probability for Miniscript Policies

- src/screens/ChoosePlanScreen/ChoosePlan.tsx
Addressing 
Active Subscription type(monthly/Yearly) required #5118
> Shows active monthly/yearly subscriptions

- src/hardware/index.ts
- src/screens/QRScreens/RegisterWithQR.tsx
- src/screens/Vault/SigningDeviceDetails.tsx
- src/services/qr/index.ts
Addressing
Keystone wallet registration failure by QR #5796
Enable Key sharing and signing for Keystone #5678
> fixes keystone vault registration failure

- src/screens/SignTransaction/SignTransactionScreen.tsx
Addressing 
App Hangs and Becomes Unresponsive When Trying to Unlock TapSigner #5968
> Fixes app unresponsive on tapsigner unlock

- Readme.md
Removed invalid apk certificate verification step.
/META-INF/HEXAWALL.RSA file was removed with introduction of APK Signature Scheme v2.
> fix: removeApkCertVerifySteps

- src/services/electrum/client.ts
Reconnect electrum node after it fails due to establishing Tor connection.
> Reconnect electrum node

- src/store/sagas/utxos.ts
- src/store/sagas/wallets.ts
Addressing #5684 
made modify labels calls asynchronous to reduce tnx loading time.
> improves vault import 

- src/services/backend/Relay.ts
- src/store/sagas/bhr.ts
Addressing #6085
This reverts commit d6af1b83b12536fd22e563959faa2ecb7eb2e249.
ref: fixes unencrypted vault.scheme storage #6089
> fixes unencrypted vault.scheme storage

- android/fastlane/Fastfile
Disabled fastlane implementation for uploading android apk to slack channel since the api endpoint is deprecated by slack.
> Disabled Fastlane Apk Upload

- src/hooks/useSettingKeeper.tsx
- src/screens/KeeperConcierge/components/AccountManagerCard.tsx
- src/screens/Vault/SignerAdvanceSettings.tsx
Hides dark mode toggle on keeper private subscription
Fixes account manager card ui for light theme
Addressing https://github.com/bithyve/bitcoin-keeper/issues/6292
> KeeperPrivateUi issues and ServerKey Restriction

- src/screens/Vault/AssignSignerType.tsx
- src/storage/realm/migrations.ts
Fixes
- Missing miniscript vault data in migration. 
- Wallet sync error due to migration failure.
- Added TapSigner in assign signer type list for unknown signers.
> Fixes migration issues and tapsigner assign signer type

- android/app/src/main/res/xml/network_security_config.xml
Removed sub-domains from android network security config which are no longer utilised.
> Clean android network security domains 

- src/utils/utilities.ts
Skips PSBY validation in case of missing bip32derivation object in PSBT input.
Addressing Error When Scanning SeedSigner and Krux QR in Keeper: Cannot read property 'forEach' of undefined. #6833
> Fixes psbt validation error
